# Generated by Django 3.2.4 on 2021-08-08 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hill_bakes', '0002_auto_20210808_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='order_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
