# Generated by Django 3.2.4 on 2021-08-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hill_bakes', '0003_userhistory_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='quantity',
        ),
    ]
