# Generated by Django 3.2.4 on 2021-08-11 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hill_bakes', '0005_auto_20210810_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descriptions', to='hill_bakes.product')),
            ],
        ),
    ]
