# Generated by Django 3.2.4 on 2021-08-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hill_bakes', '0006_productdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.DeleteModel(
            name='ProductDescription',
        ),
    ]
