# Generated by Django 3.2.4 on 2021-08-12 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hill_bakes', '0007_auto_20210811_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='producttype',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='types', to='hill_bakes.product'),
            preserve_default=False,
        ),
    ]
