# Generated by Django 3.2.4 on 2021-08-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hill_bakes', '0008_auto_20210812_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='product',
        ),
        migrations.AddField(
            model_name='producttype',
            name='product',
            field=models.ManyToManyField(to='hill_bakes.Product'),
        ),
    ]
